version: 2.1

jobs:
  build:
    docker:
      - image: node
    steps:
      - checkout
      - run:
          name: build project
          command: |
            yarn
            yarn run export
            cp -r .circleci/ __sapper__/export/.circleci/
      - persist_to_workspace:
          root: __sapper__
          paths: export/*
  deploy:
    docker:
      - image: node
    steps:
      - checkout
      - attach_workspace:
          at: __sapper__
      - add_ssh_keys:
          fingerprints:
            - 'b4:3b:29:c4:68:e8:db:82:e1:23:46:ee:e6:9b:c6:4a'
      - run:
          name: install gh-pages npm package
          command: |
            npm i -g --silent gh-pages
            git config user.email "bora.mog@gmail.com"
            git config user.name "BoryaMogila"
      - run:
          Name: Deploy static site to gh-pages branch
          command: gh-pages -t --dist __sapper__/export/

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master